import Head from 'next/head'
// import styles from '@/styles/Home.module.css'



export default function Home() {
  return (
    <div className=' w-screen h-screen flex items-center justify-center  bg-red-500'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <h1>Home page</h1>
    </div>
  )
}
