import Head from 'next/head'
import { Contact, Footer, Header, Homepage, Ourblog, Testimonial, Thetransporter, Transporter, Whatwedo, Whychoose, Whyus } from '@/containers';
import NavBar from '@/components/NavBar';
import Socialmedia from '@/components/Socialmedia';


export default function Home() {
  return (
    <div className=' w-screen h-auto flex flex-col bg-white'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Homepage/>
      <Whatwedo/>
      <Whyus/>
      <Thetransporter/>
      <Testimonial/>
      <Whychoose/>
      <Transporter/>
      <Contact/>
      <Ourblog/>
      <Footer/>
    </div>
  )
}
